
name: test_cicd # ワークフローの名前
on: # トリガー条件
    push:
        branches:
            - main

jobs:
    job1:
        name: set-up-and-build-job
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2
        
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14'
        
            - name: Install dependencies
              run: npm install
        
            - name: Build project
              run: npm run build
    
            - name: upload build artifacts #ビルド成果物アップロード
              uses: actions/upload-artifact@v4
              with:
                path: ./build/*
                
    job2: #新規作成
        runs-on: ubuntu-latest
        needs: job1 #job1が成功したら実行
        steps:
          - name: Checkout the target repository
            uses: actions/checkout@v4
            with:
              repository: 'masanori001/react_build'  # push先のリポジトリ
              ref: 'main'
              token: ${{ secrets.TOKEN_KEY }}  # GITHUB_TOKENを使って認証
    
          - name: Download build artifact
            uses: actions/download-artifact@v3
            with:
              name: 'upload build artifacts' #ダウンロード対象のArtifacts
              path: ./build/*
    
          - name: Commit and push changes to another repository
            run: |
              # git config user.name "GitHub Actions"
              # git config user.email "actions@github.com"
              git add .
              git commit -m "Add build artifacts"
              git push origin main  # 別リポジトリの`main`ブランチにpush
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_KEY }}  # GITHUB_TOKENを使って認証
